### PR TITLE
Several formats supported by 7zip were added

### PR DESCRIPTION
**Pull request by arttarasov**
Unfortunately, it was tested only with SquashFS file format.
The list of supported formats was found [here](https://github.com/FauxFaux/7-zip/blob/master/CPP/7zip/Guid.txt)

### CODE REVIEW

**Comment by adoconnection** [comment]
I belive it should work fine for other formats too, thanks for sharing

**Comment by arttarasov** [comment]
Could you please publish the new version to [NuGet](https://www.nuget.org/packages/SevenZipExtractor/)?

**Comment by adoconnection** [comment]
yep, done

Install-Package SevenZipExtractor -Version 1.0.8

**Comment by arttarasov** [comment]
Thanks, Alexander.

**Pull request merged**
