### PR TITLE
SevenZipFormat by file header signature when file extension are unknow 

### PR DESCRIPTION
**Pull request by JosePineiro**
Work with void extension
Read the file signature once.

### CODE REVIEW

**Comment by adoconnection** [comment]
Jose, I will review and merge on Monday.

As for merging all files in one assembly, this may be confusing for some people imo. When binaries are merged you can not verify they are real.

**Comment by JosePineiro** [comment]
Ok.

I do not send glue files in one assembly. Please, merge this commit with file signature function. 

One question: Can you implemented the multitasking option in 7zip library?

**Comment by adoconnection** [comment]
Hi, im super sorry for delay with merging this request

**Comment by adoconnection** [comment]
https://www.nuget.org/packages/SevenZipExtractor/1.0.11

**Comment by adoconnection** [comment]
I did some refactorings, and reverted your changes to Examples project: the idea to keep it as simple as possible. Regular person is expected to be able to write foreach and compare strings :-)

**Pull request merged**
