### PR TITLE
Use new csproj format and add .Net Standard target framework

### PR DESCRIPTION
**Pull request by WojciechNagorski**
In this PR I've:
- used 2017 `csproj` format using https://github.com/hvanbakel/CsprojToVs2017
- added .net standard target framework. Currently, the project have two target frameworks: `net45` and `netstandard2.0`.
- Updated nugets for the test project
- changed pack.ps1 script.

### CODE REVIEW

**Comment by WojciechNagorski** [comment]
If this PR will be merged, I'm going to use BenchmarkDotNet in benchmark project. I'm BenchmarkDotNet contributor, so it should be easy.

**Comment by WojciechNagorski** [comment]
In this PR I fixed also #37

**Comment by adoconnection** [comment]
merged
nuget package 1.0.15: https://www.nuget.org/packages/SevenZipExtractor/1.0.15

**Comment by WojciechNagorski** [comment]
Thanks!

**Pull request merged**
