### PR TITLE
Added further meta data to the Entry class

### PR DESCRIPTION
**Pull request by rabanti-github**
Hi,
I added the most important, additional meta data to the Entry class. This can be useful for instance to compare already existing files with files to extract in a library (e.g. CRC or date comparison.)
The additional properties are according to the available (and usefull) columns in the 7Zip file manager:

* IsEncrypted
* CreationTime
* LastWriteTime
* LastAccessTime
* CRC
* Attributes
* Comment
* HostOS
* Method (Compression)

It should be no a problem to merge. I already tested the output and it looks promising.
What do you think about this change?
Thank you in advance.

### CODE REVIEW

**Comment by rabanti-github** [comment]
The second commit (94c25a) added the "internal" keyword to the setters.  
The last two commits (ea5f127, 0673263) are only typos an no changes of code, I am sorry about this.

**Comment by adoconnection** [comment]
Hi, thank you!
 I will merge asap

**Comment by rabanti-github** [comment]
Thank you for the hard work on this project.
Please let me know if I can help you for instance with code documentation.

**Comment by adoconnection** [comment]
I wound not call it hard, but thanks anyway :)

new version of nuget is ready:
https://www.nuget.org/packages/SevenZipExtractor/1.0.12

you had a small typo with lastAccessTime, fixed it.
Is is possible for creationTime, lastWriteTime and lastAccessTime to be nulls?

**Comment by rabanti-github** [comment]
Hi
Thank you.
Missing dates are no problem in terms of crashes. If a date is missing in the archive, the library returns 01.01.0001 00:00:00 as date. There are two possibilities to cope with this:

a) The user has to check wheter the date of the archive is plausible (if date == year 0 then no date available)
b) The properties have to be made nullable (DateTime?)

However, possibility b) makes a check in SevenZipExtractor necessary. I would leave it like this for the moment (stick with possibility a).

**Pull request merged**
